### ISSUE TITLE
save sounds temporarily

### ISSUE THREAD

**Issue by OtariOboladzeSfC** [ScienceForChange/soundCollect#20]
can you save sounds with the user name or email on the server temporarily?  for sound calibration pilot day we need to save sounds with the user identifiers. 
sample:  user_123 converted sounds to parameters and server saved all sounds as:

- user_123_sound_1
- user_123_sound_2
- user_123_sdrgisughnsiugh

only for a pilot days, which will be 6 in total within 4 months.
@CarlosMillanSfC

**Comment by CarlosMillanSfC** [comment]
I can save the sounds with the timespamp (audio-2024-03-05-10:51:34.WAV) in folders with any user identification (not name because we do not store names)
- username of the email (**carlos.millan**@scienceforchange.eu) (my current pick)
- uuid (kinda **9b6fca9f-3af9-49d2-9c9f-30793bf5fbab**)
which one do you prefer? @OtariOboladzeSfC

**Comment by OtariOboladzeSfC** [comment]
your current pick looks good

**Comment by CarlosMillanSfC** [comment]
Done, whenever you process any audio it will be also uploaded to the server in a folder with the username of the email of the user and with a timestamp (date+time) to make it unique and easy to refer to the observation.
![image](https://github.com/ScienceForChange/soundCollect/assets/144032932/c7411473-9b36-4fce-ac1a-1b51f207f762)

The problems are:
- The AudioProcess is a step done BEFORE the observation is uploaded, it can make audios being uploaded and not actually being and observation (for example if you cancel the process of mapping a observation at the end)
- For the same reason the audio cant be connected with an actually observation because the observation does not exist when the processing of getting the info/parameteres of the audio to analyze/process
- This need makes the time of processing audio longer because i need to upload twice the same audio :/ can check for alternatives but im not sure how to deal with this to increment the performance
- Less important but good to know: the timestamp is stored as UTC and in Spain we use UTC +1 so the timestamp seems to be one hour behind but its normal.
